<table>
    {{-- Banner rows --}}
    <tr><td colspan="3">Medica Plus Pharmacy LMDC</td></tr>
    <tr><td colspan="3">Daily Sales Export — {{ $supplierName }}</td></tr>
    <tr><td colspan="3"></td></tr>

    {{-- Meta block --}}
    <tr>
        <td>Supplier:</td>
        <td colspan="2">{{ $supplierName }}</td>
    </tr>
    <tr>
        <td>Exported:</td>
        <td colspan="2">{{ now()->format('Y-m-d H:i:s') }}</td>
    </tr>
    <tr>
        <td>Total:</td>
        <td colspan="2">
            {{ $rows->count() }} products — {{ number_format($rows->sum('total_quantity'), 2) }} units
        </td>
    </tr>

    {{-- Spacer --}}
    <tr><td colspan="3"></td></tr>

    {{-- Table header --}}
    <tr>
        <td>#</td>
        <td>Product Name</td>
        <td>Quantity</td>
    </tr>

    {{-- Data --}}
    @foreach($rows as $i => $r)
        <tr>
            <td>{{ $i + 1 }}</td>
            <td>{{ $r->product_name }}</td>
            <td>{{ number_format($r->total_quantity, 2) }}</td>
        </tr>
    @endforeach

    {{-- Total row --}}
    <tr>
        <td colspan="2">TOTAL</td>
        <td>{{ number_format($rows->sum('total_quantity'), 2) }}</td>
    </tr>

    {{-- Footer spacer --}}
    <tr><td colspan="3"></td></tr>

    {{-- Footer --}}
    <tr>
        <td colspan="3">Generated by Medica Plus Pharmacy LMDC — {{ now()->format('Y-m-d') }}</td>
    </tr>
</table>